name: gauva_userapp
description: A Flutter project for Gauva Rider App.
publish_to: "none"

version: 1.0.7+107

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3

  # State Management
  flutter_riverpod: ^2.6.1

  # Form Handling
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.0.0
  dropdown_button2: ^2.3.9

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Functional Programming
  dartz: ^0.10.1

  # Local Storage
  flutter_secure_storage: ^9.2.4

  # UI
  ionicons: 0.2.2
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.64.0
  dotted_border: ^2.1.0
  lottie: ^3.1.0
  equatable: ^2.0.7


  # Connectivity
  connectivity_plus: ^6.1.4
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter

  pinput: ^5.0.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  location: ^8.0.0
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.0
  google_maps_cluster_manager:
    git:
      url: https://github.com/MacDeveloper1/google_maps_cluster_manager.git
      ref: fix/cluster
  collection: ^1.19.0
  dotted_line: ^3.2.3
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  widget_to_marker: ^1.0.6
  file_picker: ^10.3.3
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.0
  firebase_core: ^4.1.0
  google_sign_in: ^6.2.1
  flutter_ringtone_player: ^4.0.0+4
  vibration: ^3.1.3
  # WebSocket
  web_socket_channel: ^3.0.1
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  app_settings: ^6.1.1
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.0.0
  intl: ^0.20.2
  firebase_auth: ^6.1.3
  shimmer: ^3.0.0
  fluttertoast: ^8.2.12
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.11
  open_file: ^3.5.10
  video_player: ^2.10.1
  in_app_update: ^4.2.3

dependency_overrides:
  geolocator_android: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_gen_runner:
  json_serializable: ^6.7.1
  flutter_gen:
  mocktail: ^1.0.4

  # Linting
  flutter_lints: ^4.0.0
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.png"
  adaptive_icon_background: "transparent"
  adaptive_icon_foreground: "assets/LOGO.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/avatars/
    - assets/lottie/
    - assets/svg/
    - assets/


  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/generalsansextralight.ttf
          weight: 200
        - asset: assets/fonts/generalsanslight.ttf
          weight: 300
        - asset: assets/fonts/generalsansregular.ttf
          weight: 400
        - asset: assets/fonts/generalsansmedium.ttf
          weight: 500
        - asset: assets/fonts/generalsanssemibold.ttf
          weight: 600
        - asset: assets/fonts/generalsansbold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/interthin.ttf
          weight: 100
        - asset: assets/fonts/interextralight.ttf
          weight: 200
        - asset: assets/fonts/interlight.ttf
          weight: 300
        - asset: assets/fonts/interregular.ttf
          weight: 400
        - asset: assets/fonts/intermedium.ttf
          weight: 500
        - asset: assets/fonts/intersemibold.ttf
          weight: 600
        - asset: assets/fonts/interbold.ttf
          weight: 700
        - asset: assets/fonts/interextrabold.ttf
          weight: 800
        - asset: assets/fonts/interblack.ttf
          weight: 900

flutter_gen:
  assets:
    enabled: true
  integrations:
    lottie: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated